---
#
# Ansible managed
#
repository:
  description: Manage Proxmox PVE repositories and aspects of the server
  homepage: https://mullholland.net
  topics: cloud, system, ansible, molecule, playbook
