---
- name: Add PVE Apt signing key
  ansible.builtin.apt_key:
    url: "{{ proxmox_pve_repository_key }}"
    state: present

- name: update sources.list
  ansible.builtin.template:
    src: "etc/apt/sources.list.j2"
    dest: "/etc/apt/sources.list"
    owner: "root"
    group: "root"
    mode: '0644'
  when: proxmox_pve_enable_default_repository
  register: proxmox_pve_repository_sources_list

- name: update pve-enterprise.list
  ansible.builtin.template:
    src: "etc/apt/sources.list.d/pve-enterprise.list.j2"
    dest: "/etc/apt/sources.list.d/pve-enterprise.list"
    owner: "root"
    group: "root"
    mode: '0644'
  register: proxmox_pve_repository_enterprise_list

- name: update pve-no-subscription.list
  ansible.builtin.template:
    src: "etc/apt/sources.list.d/pve-no-subscription.list.j2"
    dest: "/etc/apt/sources.list.d/pve-no-subscription.list"
    owner: "root"
    group: "root"
    mode: '0644'
  register: proxmox_pve_repository_no_subscription_list

- name: update pve-ceph-repository.list
  ansible.builtin.template:
    src: "etc/apt/sources.list.d/pve-ceph-repository.list.j2"
    dest: "/etc/apt/sources.list.d/pve-ceph-repository.list"
    owner: "root"
    group: "root"
    mode: '0644'
  register: proxmox_pve_repository_ceph_list

- name: Update repository cache
  ansible.builtin.apt:
    update_cache: true
  when: proxmox_pve_repository_sources_list.changed or
    proxmox_pve_repository_enterprise_list.changed or
    proxmox_pve_repository_no_subscription_list.changed or
    proxmox_pve_repository_ceph_list.changed
  # Data should be refreshed immediatly for other roles which depend on them
  # Flush handlers is not used because it would potentially flush handlers,
  # which are not meant to be flushed at this point in the playbook
  tags:
    - skip_ansible_lint

- name: manage CPU govenor
  when: proxmox_pve_cpu_govenor_manage
  block:
    - name: install cpu govenor dependencies
      ansible.builtin.apt:
        name: "{{ proxmox_pve_cpu_govenor_dependencies }}"
        state: present

    - name: update cpufrequtils config
      ansible.builtin.template:
        src: "etc/default/cpufrequtils.j2"
        dest: "{{ proxmox_pve_cpu_govenor_conf }}"
        owner: "root"
        group: "root"
        mode: '0644'
      notify: restart_cpufrequtils
