---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Copy PVE Repository Template
      ansible.builtin.copy:
        content: |
            deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise
        dest: /etc/apt/sources.list.d/pve-enterprise.list
