---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_facts['distribution'] }}"
          - "ansible_distribution_major_version => {{ ansible_facts['distribution_major_version'] }}"
          - "ansible_os_family  => {{ ansible_facts['os_family'] }}"
          - "ansible_system  => {{ ansible_facts['system'] }}"

    - name: Verify PVE Apt signing key exists
      ansible.builtin.stat:
        path: "/etc/apt/keyrings/proxmox-release-{{ ansible_facts['distribution_release'] }}.gpg"
      register: verify_apt_signing_key_status
      failed_when: not verify_apt_signing_key_status.stat.exists

    - name: verify if sources.list
      ansible.builtin.lineinfile:
        name: '/etc/apt/sources.list'
        line: 'deb http://ftp.debian.org/debian {{ ansible_facts["distribution_release"] }} main contrib'
        state: present
      check_mode: true
      register: verify_repository_status
      failed_when: (verify_repository_status is changed) or (verify_repository_status is failed)

    - name: verify if pve-enterprise.list exists
      ansible.builtin.lineinfile:
        name: '/etc/apt/sources.list.d/pve-enterprise.list'
        line: '#deb [signed-by=/etc/apt/keyrings/proxmox-release-{{ ansible_facts["distribution_release"] }}.gpg] https://enterprise.proxmox.com/debian/pve {{ ansible_facts["distribution_release"] }} pve-enterprise'
        state: present
      check_mode: true
      register: verify_enterprise_repository_status
      failed_when: (verify_enterprise_repository_status is changed) or (verify_enterprise_repository_status is failed)

    - name: verify if pve-no-subscription.list exists
      ansible.builtin.lineinfile:
        name: '/etc/apt/sources.list.d/pve-no-subscription.list'
        line: 'deb [signed-by=/etc/apt/keyrings/proxmox-release-{{ ansible_facts["distribution_release"] }}.gpg] http://download.proxmox.com/debian/pve {{ ansible_facts["distribution_release"] }} pve-no-subscription'
        state: present
      check_mode: true
      register: verify_no_subscription_repository_status
      failed_when: (verify_no_subscription_repository_status is changed) or (verify_no_subscription_repository_status is failed)

    - name: verify if pve-ceph.list exists
      ansible.builtin.lineinfile:
        name: '/etc/apt/sources.list.d/pve-ceph-repository.list'
        line: '#deb [signed-by=/etc/apt/keyrings/proxmox-release-{{ ansible_facts["distribution_release"] }}.gpg] http://download.proxmox.com/debian/ceph-pacific {{ ansible_facts["distribution_release"] }} main'
        state: present
      check_mode: true
      register: verify_ceph_repository_status
      failed_when: (verify_ceph_repository_status is changed) or (verify_ceph_repository_status is failed)

    - name: verify if pve-ceph.list exists
      ansible.builtin.lineinfile:
        name: '/etc/apt/sources.list.d/pve-ceph-repository.list'
        line: '#deb [signed-by=/etc/apt/keyrings/proxmox-release-{{ ansible_facts["distribution_release"] }}.gpg] http://download.proxmox.com/debian/ceph-pacific {{ ansible_facts["distribution_release"] }} main'
        state: present
      check_mode: true
      register: verify_ceph_repository_status
      failed_when: (verify_ceph_repository_status is changed) or (verify_ceph_repository_status is failed)

    - name: Check cpufrequtils is installed
      ansible.builtin.package:
        name: "cpufrequtils"
        state: present
      register: verify_package_installed
      failed_when: (verify_package_installed is changed) or (verify_package_installed is failed)
      when: proxmox_pve_cpu_govenor_manage | default(false)

    - name: verify if cpufrequtils exists
      ansible.builtin.lineinfile:
        name: '/etc/default/cpufrequtils'
        line: 'GOVERNOR="performance"'
        state: present
      check_mode: true
      register: verify_cpufrequtils_status
      failed_when: (verify_cpufrequtils_status is changed) or (verify_cpufrequtils_status is failed)
      when: proxmox_pve_cpu_govenor_manage | default(false)
